# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
locale: fr-FR
title: "MoiJe"
description: "Pour que le moi de dans 20 ans il se souvienne de ce que j'aimais. Et qu'il en rigole !"
baseurl: / # the subpath of your site, e.g. "/blog"
url: https://iambarty.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: /images/moije-site-logo.jpg # path of site logo, e.g. "/images/logo.png"
date_format: "%d/%m/%Y"
read_time: false
words_per_minute: false
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
permalink: /:tags/:title/
markdown: kramdown
# excerpt_separator: ""
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-spotify

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
    
# Collections
collections:
  tops:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: page
      comments: false
      share: false
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: page
      comments: false
      share: false
  - scope:
      path: "_tops"
      type: tops
    values:
      layout: page
      comments: false
      share: false

# Site Author
author:
  name: Baptiste Lecornu
  picture: /images/baptiste-lecornu-photo.jpg
  links: false
#    - title: Twitter
#      url: https://twitter.com/mmistakes
#      icon: fab fa-twitter-square
#    - title: Instagram
#      url: https://instagram.com/mmistakes
#      icon: fab fa-instagram
#    - title: GitHub
#      url: https://github.com/mmistakes
#      icon: fab fa-github-square

# Footer Links
footer_links: false
#  - title: Twitter
#    url: https://twitter.com/mmistakes
#    icon: fab fa-twitter-square
#  - title: Instagram
#    url: https://instagram.com/mmistakes
#    icon: fab fa-instagram
#  - title: GitHub
#    url: https://github.com/mmistakes
#    icon: fab fa-github-square
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square
# site.copyright: "Ce site est édité par *me, myself, and I*. Et beaucoup d'aide de [Jekill] (https://jekyllrb.com/) a [So Simple] (https://github.com/mmistakes/so-simple-theme).
